// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package queries

import (
	"context"
)

const addChatMember = `-- name: AddChatMember :one
INSERT INTO chat_members (chat_id, user_id)
VALUES ($1, $2)
RETURNING chat_id, user_id, joined_at
`

type AddChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chat_id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) (ChatMember, error) {
	row := q.db.QueryRow(ctx, addChatMember, arg.ChatID, arg.UserID)
	var i ChatMember
	err := row.Scan(&i.ChatID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (name, is_group)
VALUES ($1, $2)
RETURNING id, name, is_group, created_at, updated_at
`

type CreateChatParams struct {
	Name    string `db:"name" json:"name"`
	IsGroup bool   `db:"is_group" json:"is_group"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Name, arg.IsGroup)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ChatID   int64  `db:"chat_id" json:"chat_id"`
	SenderID int64  `db:"sender_id" json:"sender_id"`
	Content  string `db:"content" json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const findDirectChatsBetweenUsers = `-- name: FindDirectChatsBetweenUsers :one
SELECT c.id, c.name, c.is_group, c.created_at, c.updated_at
FROM chats c
WHERE c.is_group = false
  AND EXISTS (
    SELECT 1 FROM chat_members cm1
    WHERE cm1.chat_id = c.id AND cm1.user_id = $1
  )
  AND EXISTS (
    SELECT 1 FROM chat_members cm2
    WHERE cm2.chat_id = c.id AND cm2.user_id = $2
  )
  AND (
    SELECT COUNT(*) FROM chat_members cm3
    WHERE cm3.chat_id = c.id
  ) = 2
LIMIT 1
`

type FindDirectChatsBetweenUsersParams struct {
	UserID   int64 `db:"user_id" json:"user_id"`
	UserID_2 int64 `db:"user_id_2" json:"user_id_2"`
}

func (q *Queries) FindDirectChatsBetweenUsers(ctx context.Context, arg FindDirectChatsBetweenUsersParams) (Chat, error) {
	row := q.db.QueryRow(ctx, findDirectChatsBetweenUsers, arg.UserID, arg.UserID_2)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, name, is_group, created_at, updated_at FROM chats
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS (
    SELECT 1 FROM chat_members
    WHERE chat_id = $1 AND user_id = $2
)
`

type IsChatMemberParams struct {
	ChatID int64 `db:"chat_id" json:"chat_id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, chat_id, sender_id, content, created_at FROM messages
WHERE chat_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChatMessages(ctx context.Context, chatID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, listChatMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersChats = `-- name: ListUsersChats :many
SELECT c.id, c.name, c.is_group, c.created_at, c.updated_at
FROM chats c
JOIN chat_members cm ON cm.chat_id = c.id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC
`

func (q *Queries) ListUsersChats(ctx context.Context, userID int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listUsersChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsGroup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
