// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64              `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	Nickname     string             `db:"nickname" json:"nickname"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	LastSeen     pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
